'use client'

import React, { useState, useEffect, useMemo } from 'react'
import { CheckCircle2, Circle, ClipboardList, Download, Share2, Search, Zap, Shield, Smartphone, Globe, FileCode, Check } from 'lucide-react'
import BreadcrumbSchema from '@/components/seo/BreadcrumbSchema'
import ToolSchema from '@/components/seo/ToolSchema'
import ToolInfo from '@/components/sections/ToolInfo'
import AdSlot from '@/components/ads/AdSlot'

const checklistData = [
  {
    category: 'Crawlability & Indexing',
    icon: Globe,
    items: [
      { id: 'xml-sitemap', text: 'XML Sitemap is present and submitted to Google Search Console', detail: 'Ensures Google can find all your pages.' },
      { id: 'robots-txt', text: 'Robots.txt is optimized and not blocking critical resources', detail: 'Prevents crawling of sensitive or low-value areas.' },
      { id: 'canonical-tags', text: 'Self-referencing canonical tags are present on all pages', detail: 'Prevents duplicate content issues.' },
      { id: 'noindex-check', text: 'Noindex tags are only used on intended private pages', detail: 'Prevents accidental de-indexing of key pages.' },
      { id: 'broken-links', text: 'Check for 404 errors and broken internal links', detail: 'Improves user experience and crawl efficiency.' }
    ]
  },
  {
    category: 'Core Web Vitals & Speed',
    icon: Zap,
    items: [
      { id: 'lcp-check', text: 'Largest Contentful Paint (LCP) is under 2.5 seconds', detail: 'Measures perceived loading speed.' },
      { id: 'inp-check', text: 'Interaction to Next Paint (INP) is under 200ms', detail: 'Measures site responsiveness.' },
      { id: 'cls-check', text: 'Cumulative Layout Shift (CLS) is under 0.1', detail: 'Measures visual stability.' },
      { id: 'image-optimization', text: 'All images are compressed and use Next-Gen formats (WebP/AVIF)', detail: 'Reduces payload and improves speed.' },
      { id: 'lazy-loading', text: 'Lazy loading is implemented for off-screen images', detail: 'Saves bandwidth and improves initial load time.' }
    ]
  },
  {
    category: 'On-Page & Content',
    icon: Search,
    items: [
      { id: 'title-length', text: 'Titles are between 50-60 characters and contain keywords', detail: 'Optimal length for search result snippets.' },
      { id: 'meta-desc', text: 'Meta descriptions are between 120-160 characters', detail: 'Drives click-through rate (CTR).' },
      { id: 'heading-hierarchy', text: 'Pages have exactly one H1 and a logical H2-H3 hierarchy', detail: 'Helps Google understand content structure.' },
      { id: 'alt-text', text: 'All images have descriptive, keyword-rich Alt text', detail: 'Critical for accessibility and Image Search SEO.' },
      { id: 'internal-linking', text: 'Strategic internal links connect related content', detail: 'Distributes "link equity" across the site.' }
    ]
  },
  {
    category: 'Architecture & Security',
    icon: Shield,
    items: [
      { id: 'https-check', text: 'Site is served over HTTPS with a valid SSL certificate', detail: 'A core ranking signal and trust factor.' },
      { id: 'mobile-friendly', text: 'Site passes the Google Mobile-Friendly test', detail: 'Google uses mobile-first indexing.' },
      { id: 'structured-data', text: 'JSON-LD Schema is implemented (Breadcrumbs, FAQ, etc.)', detail: 'Enables Rich Snippets in search results.' },
      { id: 'social-meta', text: 'Open Graph (OG) and Twitter card tags are configured', detail: 'Ensures links look professional when shared.' },
      { id: 'site-security', text: 'Security headers (CSP, HSTS, X-Frame-Options) are active', detail: 'Protects users and site reputation.' }
    ]
  }
]

export default function SeoAuditChecklist() {
  const [checkedItems, setCheckedItems] = useState<string[]>([])
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    const saved = localStorage.getItem('wtk_seo_checklist')
    if (saved) setCheckedItems(JSON.parse(saved))
  }, [])

  const toggleItem = (id: string) => {
    const newItems = checkedItems.includes(id)
      ? checkedItems.filter(i => i !== id)
      : [...checkedItems, id]
    setCheckedItems(newItems)
    localStorage.setItem('wtk_seo_checklist', JSON.stringify(newItems))
  }

  const totalItems = checklistData.reduce((acc, cat) => acc + cat.items.length, 0)
  const progress = Math.round((checkedItems.length / totalItems) * 100)

  const copyAsMarkdown = () => {
    let md = '# Technical SEO Audit Checklist\n\n'
    checklistData.forEach(cat => {
      md += `## ${cat.category}\n`
      cat.items.forEach(item => {
        const isChecked = checkedItems.includes(item.id) ? '[x]' : '[ ]'
        md += `${isChecked} ${item.text}\n`
      })
      md += '\n'
    })
    md += '---\n*Generated by WebToolkit Pro SEO Audit Tool*'
    navigator.clipboard.writeText(md)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-slate-950 py-12 px-4 sm:px-6 lg:px-8 transition-colors duration-300">
      <BreadcrumbSchema name="Technical SEO Audit Checklist" slug="seo-audit-checklist" />
      <ToolSchema 
        name="Technical SEO Audit Checklist" 
        description="A comprehensive, interactive checklist for auditing your website's SEO health. Covers crawlability, indexing, speed, and content structure."
        slug="seo-audit-checklist"
        steps={[
          "Browse through the four core audit categories: Crawlability, Speed, On-Page, and Architecture.",
          "Check off each item as you verify it on your production website.",
          "Monitor your real-time 'Audit Progress' at the top of the page.",
          "Copy the results as Markdown to share with your development team."
        ]}
      />
      
      <div className="max-w-4xl mx-auto">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
          <div className="flex items-center gap-4">
            <div className="p-4 bg-blue-600 rounded-2xl shadow-lg shadow-blue-600/20 text-white">
              <ClipboardList className="w-8 h-8" />
            </div>
            <div>
              <h1 className="text-3xl font-extrabold text-gray-900 dark:text-white tracking-tight">Technical SEO Audit</h1>
              <p className="text-gray-500 dark:text-slate-400">The ultimate checklist for perfect search engine visibility</p>
            </div>
          </div>
          
          <button 
            onClick={copyAsMarkdown}
            className="flex items-center gap-2 px-6 py-3 bg-white dark:bg-slate-900 text-gray-700 dark:text-slate-300 font-bold rounded-xl border border-gray-200 dark:border-slate-800 hover:shadow-md transition-all whitespace-nowrap"
          >
            {copied ? <Check className="w-5 h-5 text-green-500" /> : <FileCode className="w-5 h-5" />}
            <span>{copied ? 'Markdown Copied' : 'Copy as Markdown'}</span>
          </button>
        </div>
        <AdSlot className="mb-12" />

        {/* Progress Bar */}
        <div className="bg-white dark:bg-slate-900 rounded-3xl p-8 border border-gray-100 dark:border-slate-800 mb-12 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <span className="text-sm font-bold text-gray-400 dark:text-slate-500 uppercase tracking-widest">Audit Progress</span>
            <span className="text-2xl font-black text-blue-600 dark:text-blue-400">{progress}%</span>
          </div>
          <div className="w-full h-4 bg-gray-100 dark:bg-slate-800 rounded-full overflow-hidden">
            <div 
              className="h-full bg-gradient-to-r from-blue-500 to-blue-700 transition-all duration-500 ease-out"
              style={{ width: `${progress}%` }}
            />
          </div>
        </div>

        {/* Checklist Categories */}
        <div className="space-y-8">
          {checklistData.map((cat, catIdx) => (
            <div key={catIdx} className="bg-white dark:bg-slate-900 rounded-3xl border border-gray-100 dark:border-slate-800 overflow-hidden shadow-sm">
              <div className="p-6 border-b border-gray-50 dark:border-slate-800 bg-gray-50/50 dark:bg-slate-900/50 flex items-center gap-3">
                <cat.icon className="w-6 h-6 text-blue-600 dark:text-blue-400" />
                <h2 className="text-lg font-bold text-gray-900 dark:text-white">{cat.category}</h2>
              </div>
              <div className="p-6 space-y-4">
                {cat.items.map((item) => (
                  <div 
                    key={item.id}
                    onClick={() => toggleItem(item.id)}
                    className="flex items-start gap-4 p-4 rounded-2xl hover:bg-gray-50 dark:hover:bg-slate-800/50 cursor-pointer transition-all border border-transparent hover:border-gray-100 dark:hover:border-slate-700 group"
                  >
                    <div className="mt-1 shrink-0">
                      {checkedItems.includes(item.id) ? (
                        <CheckCircle2 className="w-6 h-6 text-green-500 fill-green-50 dark:fill-green-900/10" />
                      ) : (
                        <Circle className="w-6 h-6 text-gray-300 dark:text-slate-600 group-hover:text-blue-500" />
                      )}
                    </div>
                    <div>
                      <h3 className={`font-bold leading-snug transition-colors ${checkedItems.includes(item.id) ? 'text-gray-400 dark:text-slate-600 line-through' : 'text-gray-900 dark:text-white'}`}>
                        {item.text}
                      </h3>
                      <p className="text-sm text-gray-500 dark:text-slate-400 mt-1">
                        {item.detail}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Informational Footer */}
        <div className="mt-16 text-center text-gray-400 dark:text-slate-600 text-sm">
          <p>This checklist is designed for technical SEO audits in 2026. Regularly updated based on Google Search algorithm changes.</p>
        </div>
        <AdSlot className="mt-16" />

        <ToolInfo 
          title="Technical SEO Audit Checklist"
          description="The WebToolkit Pro SEO Audit Checklist is an interactive, professional-grade utility for webmasters and digital marketers. It systematizes the complex process of verifying a website's technical health, ensuring that no critical ranking factor is overlooked during a site launch or migration."
          howItWorks="Our checklist is divided into four strategic pillars: Crawlability & Indexing, Core Web Vitals, On-Page Structure, and Architecture & Security. The tool uses local storage to persist your progress across sessions, allowing you to perform deep audits over multiple days. It also features a 'Markdown Export' function, enabling seamless collaboration between SEO teams and developers."
          features={[
            "Interactive progress tracking with real-time visualization",
            "Covers 20+ critical technical SEO ranking factors",
            "Localized persistence (Progress saved in browser)",
            "One-click 'Markdown Export' for project documentation",
            "High-authority detail blocks for each audit point",
            "100% Free: Comprehensive resource for technical teams"
          ]}
          faqs={[
            {
              q: "How often should I perform an SEO audit?",
              a: "We recommend a full technical audit at least once per quarter, or immediately following any major site update or infrastructure migration."
            },
            {
              q: "What is the most critical item on this list?",
              a: "While all items are important, 'Crawlability & Indexing' (Sitemaps and Robots.txt) is foundational. If Google cannot crawl your site, no other optimization matters."
            },
            {
              q: "Does passing this checklist guarantee #1 rankings?",
              a: "No. SEO is a competitive field. This checklist ensures your site is technically sound and has a 'seat at the table,' but ranking #1 requires superior content and high-quality backlinks."
            },
            {
              q: "Is this checklist updated for 2026?",
              a: "Yes. Our audit points include modern requirements like INP (Interaction to Next Paint) and AI-bot management in robots.txt."
            }
          ]}
        />
      </div>
    </div>
  )
}
