'use client'

import React, { useState } from 'react'
import { FileCode, Copy, Trash2, Check, ArrowRightLeft, Code } from 'lucide-react'

export default function JsonToGo() {
  const [json, setJson] = useState('{\n  "id": 1,\n  "name": "Jane Doe",\n  "active": true,\n  "tags": ["admin", "staff"]\n}')
  const [output, setOutput] = useState('')
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)

  const convertJson = () => {
    try {
      const parsed = JSON.parse(json)
      let goStruct = 'type AutoGenerated struct {\n'
      
      for (const [key, val] of Object.entries(parsed)) {
        const titleKey = key.charAt(0).toUpperCase() + key.slice(1)
        let goType = 'string'
        
        if (typeof val === 'number') goType = Number.isInteger(val) ? 'int' : 'float64'
        if (typeof val === 'boolean') goType = 'bool'
        if (Array.isArray(val)) {
          const innerType = typeof val[0] === 'number' ? 'int' : 'string'
          goType = `[]${innerType}`
        }
        
        goStruct += `\t${titleKey} ${goType} \`json:"${key}"\`\n`
      }
      
      goStruct += '}'
      setOutput(goStruct)
      setError('')
    } catch (e: any) {
      setError(e.message)
      setOutput('')
    }
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest px-2">JSON Source</label>
          <textarea
            value={json}
            onChange={(e) => setJson(e.target.value)}
            className="w-full h-[400px] p-6 font-mono text-xs bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-800 rounded-3xl outline-none resize-none dark:text-white transition-all shadow-sm"
          />
        </div>
        <div className="space-y-4 h-full flex flex-col">
          <div className="flex items-center justify-between px-2">
            <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Go Struct Output</label>
            {output && (
              <button 
                onClick={handleCopy}
                className="text-xs font-bold text-blue-600 flex items-center gap-1.5 px-3 py-1.5 bg-blue-50 dark:bg-blue-900/10 rounded-lg"
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </button>
            )}
          </div>
          <textarea
            readOnly
            value={output || error}
            className="w-full flex-grow p-6 font-mono text-xs bg-[#0F172A] text-blue-400 border border-slate-800 rounded-3xl outline-none resize-none"
          />
        </div>
      </div>
      <div className="flex justify-center">
        <button
          onClick={convertJson}
          className="px-12 py-4 bg-blue-600 text-white rounded-2xl font-black hover:scale-105 transition-all shadow-xl shadow-blue-500/20 uppercase tracking-widest text-xs"
        >
          Convert to Go Struct
        </button>
      </div>
    </div>
  )
}
