import dynamic from 'next/dynamic'
import React, { ComponentType } from 'react'

export const TOOL_COMPONENTS: Record<string, ComponentType<any>> = {
  'json-to-code-generator': dynamic(() => import('../components/tools/instances/JsonToCodeGenerator'), { ssr: false }),
  'json-yaml-jsonl-converter': dynamic(() => import('../components/tools/instances/JsonYamlJsonlConverter'), { ssr: false }),
  'bulk-uuid-v4-v7-generator': dynamic(() => import('../components/tools/instances/BulkUuidGenerator'), { ssr: false }),
  'password-entropy-tester': dynamic(() => import('../components/tools/instances/PasswordEntropyTester'), { ssr: false }),
  'csv-json-xml-converter': dynamic(() => import('../components/tools/instances/CsvJsonXmlConverter'), { ssr: false }),

  
  // Wave 2 Consolidated Masters
  'schema-markup-generator': dynamic(() => import('../components/tools/instances/SchemaMarkupGenerator'), { ssr: false }),
  'sql-toolkit': dynamic(() => import('../components/tools/instances/SqlToolkit'), { ssr: false }),
  'markdown-html-converter': dynamic(() => import('../components/tools/instances/MarkdownHtmlConverter'), { ssr: false }),

  // Batch 1: Core Utilities
  'what-is-my-ip': dynamic(() => import('../components/tools/instances/WhatIsMyIP'), { ssr: false }),
  'js-minifier': dynamic(() => import('../components/tools/instances/JsMinifier'), { ssr: false }),
  'meta-tag-generator': dynamic(() => import('../components/tools/instances/MetaTagGenerator'), { ssr: false }),
  'lorem-ipsum': dynamic(() => import('../components/tools/instances/LoremIpsum'), { ssr: false }),
  'robots-generator': dynamic(() => import('../components/tools/instances/RobotsGenerator'), { ssr: false }),
  'hash-generator': dynamic(() => import('../components/tools/instances/HashGenerator'), { ssr: false }),
  
  // Batch 2: SEO & Validation
  'sitemap-validator': dynamic(() => import('../components/tools/instances/SitemapValidator'), { ssr: false }),
  'redirect-checker': dynamic(() => import('../components/tools/instances/RedirectChecker'), { ssr: false }),
  'api-latency-calculator': dynamic(() => import('../components/tools/instances/ApiLatencyCalculator'), { ssr: false }),
  'adsense-calculator': dynamic(() => import('../components/tools/instances/AdSenseCalculator'), { ssr: false }),
  'base64-encoder': dynamic(() => import('../components/tools/instances/Base64Encoder'), { ssr: false }),
  'xml-to-yaml': dynamic(() => import('../components/tools/instances/XmlToYaml'), { ssr: false }),
  'binary-converter': dynamic(() => import('../components/tools/instances/BinaryConverter'), { ssr: false }),
  'case-converter': dynamic(() => import('../components/tools/instances/CaseConverter'), { ssr: false }),
  'css-unit-converter': dynamic(() => import('../components/tools/instances/CssUnitConverter'), { ssr: false }),
  'url-encoder': dynamic(() => import('../components/tools/instances/UrlEncoder'), { ssr: false }),
  
  // Batch 3: Design & Media
  'cdn-readiness-tester': dynamic(() => import('../components/tools/instances/CdnReadinessTester'), { ssr: false }),
  'color-contrast': dynamic(() => import('../components/tools/instances/ColorContrast'), { ssr: false }),
  'color-picker': dynamic(() => import('../components/tools/instances/ColorPicker'), { ssr: false }),
  'html-encoder': dynamic(() => import('../components/tools/instances/HtmlEncoder'), { ssr: false }),
  'timestamp-converter': dynamic(() => import('../components/tools/instances/TimestampConverter'), { ssr: false }),
  'core-web-vitals-guide': dynamic(() => import('../components/tools/instances/CoreWebVitalsGuide'), { ssr: false }),
  'robots-txt-templates': dynamic(() => import('../components/tools/instances/RobotsTemplates'), { ssr: false }),
  'seo-audit-checklist': dynamic(() => import('../components/tools/instances/SeoAuditChecklist'), { ssr: false }),
  
  // Batch 4: Formatting & Code
  'social-preview-tester': dynamic(() => import('../components/tools/instances/SocialPreviewTester'), { ssr: false }),
  'question-explorer': dynamic(() => import('../components/tools/instances/QuestionExplorer'), { ssr: false }),
  'html-beautifier': dynamic(() => import('../components/tools/instances/HtmlBeautifier'), { ssr: false }),
  'css-formatter': dynamic(() => import('../components/tools/instances/CssFormatter'), { ssr: false }),
  'regex-tester': dynamic(() => import('../components/tools/instances/RegexTester'), { ssr: false }),
  'regex-explainer': dynamic(() => import('../components/tools/instances/RegexExplainer'), { ssr: false }),
  'jwt-decoder': dynamic(() => import('../components/tools/instances/JwtDecoder'), { ssr: false }),
  'jwt-debugger': dynamic(() => import('../components/tools/instances/JwtDecoder'), { ssr: false }),
  'jwt-signer': dynamic(() => import('../components/tools/instances/JwtSigner'), { ssr: false }),
  'cron-generator': dynamic(() => import('../components/tools/instances/CronGenerator'), { ssr: false }),
  'diff-checker': dynamic(() => import('../components/tools/instances/CodeDiff'), { ssr: false }),
  'code-diff': dynamic(() => import('../components/tools/instances/CodeDiff'), { ssr: false }),
  'css-gradient-generator': dynamic(() => import('../components/tools/instances/CssGradientGenerator'), { ssr: false }),
  'llms-txt-generator': dynamic(() => import('../components/tools/instances/LlmsTxtGenerator'), { ssr: false }),
  'slug-generator': dynamic(() => import('../components/tools/instances/SlugGenerator'), { ssr: false }),
  'htaccess-generator': dynamic(() => import('../components/tools/instances/HtaccessGenerator'), { ssr: false }),
  'favicon-generator': dynamic(() => import('../components/tools/instances/FaviconGenerator'), { ssr: false }),
  'xml-formatter': dynamic(() => import('../components/tools/instances/XmlFormatter'), { ssr: false }),
  'xml-minifier': dynamic(() => import('../components/tools/instances/XmlMinifier'), { ssr: false }),
  'text-cleaner': dynamic(() => import('../components/tools/instances/TextCleaner'), { ssr: false }),
  'qr-code-generator': dynamic(() => import('../components/tools/instances/QrCodeGenerator'), { ssr: false }),
  'php-serializer': dynamic(() => import('../components/tools/instances/PhpSerializer'), { ssr: false }),
  'image-resizer': dynamic(() => import('../components/tools/instances/ImageResizer'), { ssr: false }),

  // Batch 5: Security & Data
  'xss-scanner': dynamic(() => import('../components/tools/instances/XssScanner'), { ssr: false }),
  'yaml-to-json': dynamic(() => import('../components/tools/instances/YamlToJson'), { ssr: false }),
  'aes-encryption': dynamic(() => import('../components/tools/instances/AesEncryption'), { ssr: false }),
  'sri-hasher': dynamic(() => import('../components/tools/instances/SriHasher'), { ssr: false }),
  'csp-builder': dynamic(() => import('../components/tools/instances/CspBuilder'), { ssr: false }),
  'file-checksum': dynamic(() => import('../components/tools/instances/FileChecksum'), { ssr: false }),
  'permissions-policy': dynamic(() => import('../components/tools/instances/PermissionsPolicy'), { ssr: false }),
  'meta-length-checker': dynamic(() => import('../components/tools/instances/MetaLengthChecker'), { ssr: false }),
  'heading-visualizer': dynamic(() => import('../components/tools/instances/HeadingVisualizer'), { ssr: false }),
  'og-debugger': dynamic(() => import('../components/tools/instances/OgDebugger'), { ssr: false }),
  'twitter-card-gen': dynamic(() => import('../components/tools/instances/TwitterCardGen'), { ssr: false }),
  'nginx-generator': dynamic(() => import('../components/tools/instances/NginxGenerator'), { ssr: false }),
  'docker-compose-gen': dynamic(() => import('../components/tools/instances/DockerComposeGen'), { ssr: false }),
  'dotenv-generator': dynamic(() => import('../components/tools/instances/DotenvGenerator'), { ssr: false }),
  'css-shadow-gen': dynamic(() => import('../components/tools/instances/CssShadowGen'), { ssr: false }),
  'pwa-manifest': dynamic(() => import('../components/tools/instances/PwaManifest'), { ssr: false }),
  'emoji-picker': dynamic(() => import('../components/tools/instances/EmojiPicker'), { ssr: false }),
  'readability-checker': dynamic(() => import('../components/tools/instances/ReadabilityChecker'), { ssr: false }),
  'base64-to-image': dynamic(() => import('../components/tools/instances/Base64ToImage'), { ssr: false }),
  'image-to-base64': dynamic(() => import('../components/tools/instances/ImageToBase64'), { ssr: false }),
  'html-to-markdown': dynamic(() => import('../components/tools/instances/HtmlToMarkdown'), { ssr: false }),
  'url-parser': dynamic(() => import('../components/tools/instances/UrlParser'), { ssr: false }),
  'ua-parser': dynamic(() => import('../components/tools/instances/UaParser'), { ssr: false }),
  'ascii-art': dynamic(() => import('../components/tools/instances/AsciiArt'), { ssr: false }),
  'morse-code': dynamic(() => import('../components/tools/instances/MorseCode'), { ssr: false }),
  'html-entities': dynamic(() => import('../components/tools/instances/HtmlEntities'), { ssr: false }),
  'text-similarity': dynamic(() => import('../components/tools/instances/TextSimilarity'), { ssr: false }),
  'keyword-density': dynamic(() => import('../components/tools/instances/KeywordDensity'), { ssr: false }),
  'slug-optimizer': dynamic(() => import('../components/tools/instances/SlugOptimizer'), { ssr: false }),
  'title-case': dynamic(() => import('../components/tools/instances/TitleCase'), { ssr: false }),
  'css-minifier': dynamic(() => import('../components/tools/instances/CssMinifier'), { ssr: false }),
  'html-minifier': dynamic(() => import('../components/tools/instances/HtmlMinifier'), { ssr: false }),
  'js-obfuscator': dynamic(() => import('../components/tools/instances/JsObfuscator'), { ssr: false }),
  'js-evaluator': dynamic(() => import('../components/tools/instances/JsEvaluator'), { ssr: false }),
  'curl-converter': dynamic(() => import('../components/tools/instances/CurlConverter'), { ssr: false }),
  'json-schema-gen': dynamic(() => import('../components/tools/instances/JsonSchemaGen'), { ssr: false }),
  'data-anonymizer': dynamic(() => import('../components/tools/instances/DataAnonymizer'), { ssr: false }),
  'dom-analyzer': dynamic(() => import('../components/tools/instances/DomAnalyzer'), { ssr: false }),
  'html-table-to-json': dynamic(() => import('../components/tools/instances/HtmlTableToJson'), { ssr: false }),
  'cron-descriptor': dynamic(() => import('../components/tools/instances/CronDescriptor'), { ssr: false }),
  'percentage-calc': dynamic(() => import('../components/tools/instances/PercentageCalc'), { ssr: false }),
  'aspect-ratio-calc': dynamic(() => import('../components/tools/instances/AspectRatioCalc'), { ssr: false }),
  'rgba-to-hex': dynamic(() => import('../components/tools/instances/RgbaToHex'), { ssr: false }),
  'hex-to-rgb': dynamic(() => import('../components/tools/instances/HexToRgb'), { ssr: false }),
  'px-to-rem': dynamic(() => import('../components/tools/instances/PxToRem'), { ssr: false }),
  'rem-to-px': dynamic(() => import('../components/tools/instances/RemToPx'), { ssr: false }),
  'binary-to-decimal': dynamic(() => import('../components/tools/instances/BinaryToDecimal'), { ssr: false }),
  'decimal-to-binary': dynamic(() => import('../components/tools/instances/DecimalToBinary'), { ssr: false }),
  'binary-to-hex': dynamic(() => import('../components/tools/instances/BinaryToHex'), { ssr: false }),
  'hex-to-binary': dynamic(() => import('../components/tools/instances/HexToBinary'), { ssr: false }),
  'text-to-binary': dynamic(() => import('../components/tools/instances/TextToBinary'), { ssr: false }),
  'binary-to-text': dynamic(() => import('../components/tools/instances/BinaryToText'), { ssr: false }),
  'word-counter': dynamic(() => import('../components/tools/instances/WordCounter'), { ssr: false }),
  'character-counter': dynamic(() => import('../components/tools/instances/CharacterCounter'), { ssr: false }),
  'line-counter': dynamic(() => import('../components/tools/instances/LineCounter'), { ssr: false }),
  'whitespace-remover': dynamic(() => import('../components/tools/instances/WhitespaceRemover'), { ssr: false }),
  'duplicate-line-remover': dynamic(() => import('../components/tools/instances/DuplicateLineRemover'), { ssr: false }),
  'text-reverser': dynamic(() => import('../components/tools/instances/TextReverser'), { ssr: false }),
  'case-inverter': dynamic(() => import('../components/tools/instances/CaseInverter'), { ssr: false }),
  'rot13-cipher': dynamic(() => import('../components/tools/instances/Rot13Cipher'), { ssr: false }),
  'rsa-key-gen': dynamic(() => import('../components/tools/instances/RsaKeyGen'), { ssr: false }),
  'random-user-gen': dynamic(() => import('../components/tools/instances/RandomUserGen'), { ssr: false }),
  'credit-card-validator': dynamic(() => import('../components/tools/instances/CreditCardValidator'), { ssr: false }),
  'iban-validator': dynamic(() => import('../components/tools/instances/IbanValidator'), { ssr: false }),
  'nanoid-gen': dynamic(() => import('../components/tools/instances/NanoidGen'), { ssr: false }),
  'barcode-gen': dynamic(() => import('../components/tools/instances/BarcodeGen'), { ssr: false }),
  'svg-optimizer': dynamic(() => import('../components/tools/instances/SvgOptimizer'), { ssr: false }),
  'domain-age-checker': dynamic(() => import('../components/tools/instances/DomainAgeChecker'), { ssr: false }),
  'subnet-calculator': dynamic(() => import('../components/tools/instances/SubnetCalculator'), { ssr: false }),
  'port-scanner': dynamic(() => import('../components/tools/instances/PortScanner'), { ssr: false }),
  'contrast-checker': dynamic(() => import('../components/tools/instances/ContrastChecker'), { ssr: false }),
  'bcrypt-hasher': dynamic(() => import('../components/tools/instances/BcryptHasher'), { ssr: false }),
  'argon2-hasher': dynamic(() => import('../components/tools/instances/Argon2Hasher'), { ssr: false }),
  'scrypt-hasher': dynamic(() => import('../components/tools/instances/ScryptHasher'), { ssr: false }),
  'hmac-generator': dynamic(() => import('../components/tools/instances/HmacGenerator'), { ssr: false }),
  'dns-propagation': dynamic(() => import('../components/tools/instances/DnsPropagation'), { ssr: false }),
  'ssl-checker': dynamic(() => import('../components/tools/instances/SslChecker'), { ssr: false }),
  'ping-test': dynamic(() => import('../components/tools/instances/PingTest'), { ssr: false }),
  'whois-lookup': dynamic(() => import('../components/tools/instances/WhoisLookup'), { ssr: false }),
  'http-headers-inspector': dynamic(() => import('../components/tools/instances/HttpHeadersInspector'), { ssr: false }),
  'broken-link-checker': dynamic(() => import('../components/tools/instances/BrokenLinkChecker'), { ssr: false }),
  'site-audit-pro': dynamic(() => import('../components/tools/instances/SiteAuditPro'), { ssr: false }),
  'sitemap-generator': dynamic(() => import('../components/tools/instances/SitemapGenerator'), { ssr: false }),
  'robots-validator': dynamic(() => import('../components/tools/instances/RobotsValidator'), { ssr: false }),
  'load-time-estimator': dynamic(() => import('../components/tools/instances/LoadTimeEstimator'), { ssr: false }),
  'responsive-checker-pro': dynamic(() => import('../components/tools/instances/ResponsiveCheckerPro'), { ssr: false }),
  'color-blind-simulator': dynamic(() => import('../components/tools/instances/ColorBlindSimulator'), { ssr: false }),
  'image-compressor-pro': dynamic(() => import('../components/tools/instances/ImageCompressorPro'), { ssr: false }),
  'pdf-to-text-extractor': dynamic(() => import('../components/tools/instances/PdfToTextExtractor'), { ssr: false }),
  'text-to-speech-pro': dynamic(() => import('../components/tools/instances/TextToSpeechPro'), { ssr: false }),
  'alt-text-auditor': dynamic(() => import('../components/tools/instances/AltTextAuditor'), { ssr: false }),
  'alt-text-audit': dynamic(() => import('../components/tools/instances/AltTextAuditor'), { ssr: false }),
  'authority-simulator': dynamic(() => import('../components/tools/instances/AuthoritySimulator'), { ssr: false }),
  'authority-simulation': dynamic(() => import('../components/tools/instances/AuthoritySimulator'), { ssr: false }),
  'browser-compat-checker': dynamic(() => import('../components/tools/instances/BrowserCompatChecker'), { ssr: false }),
  'browser-compat': dynamic(() => import('../components/tools/instances/BrowserCompatChecker'), { ssr: false }),
  'canonical-checker': dynamic(() => import('../components/tools/instances/CanonicalChecker'), { ssr: false }),
  'hreflang-generator': dynamic(() => import('../components/tools/instances/HreflangGenerator'), { ssr: false }),
  'snippet-preview': dynamic(() => import('../components/tools/instances/SnippetPreview'), { ssr: false }),
  'webhook-visualizer': dynamic(() => import('../components/tools/instances/WebhookVisualizer'), { ssr: false }),
  'storage-auditor': dynamic(() => import('../components/tools/instances/StorageAuditor'), { ssr: false }),
  'header-inspector': dynamic(() => import('../components/tools/instances/HttpHeadersInspector'), { ssr: false }),
  'ip-geolocation': dynamic(() => import('../components/tools/instances/WhatIsMyIP'), { ssr: false }),
  'mobile-meta-gen': dynamic(() => import('../components/tools/instances/MetaTagGenerator'), { ssr: false }),
  'redirect-chain-finder': dynamic(() => import('../components/tools/instances/RedirectChecker'), { ssr: false }),
  'cdn-finder': dynamic(() => import('../components/tools/instances/CdnReadinessTester'), { ssr: false }),
  'data-masking': dynamic(() => import('../components/tools/instances/DataAnonymizer'), { ssr: false }),
  'git-helper': dynamic(() => import('../components/tools/instances/GitHelper'), { ssr: false }),
  'cache-header-gen': dynamic(() => import('../components/tools/instances/NginxGenerator'), { ssr: false }),
  'hsts-gen': dynamic(() => import('../components/tools/instances/CspBuilder'), { ssr: false }),
  'js-execution-audit': dynamic(() => import('../components/tools/instances/SiteAuditPro'), { ssr: false }),
  'resource-priority': dynamic(() => import('../components/tools/instances/MetaTagGenerator'), { ssr: false }),
  'network-throttling': dynamic(() => import('../components/tools/instances/ApiLatencyCalculator'), { ssr: false }),
  'compression-test': dynamic(() => import('../components/tools/instances/SiteAuditPro'), { ssr: false }),
  'critical-css-gen': dynamic(() => import('../components/tools/instances/CssMinifier'), { ssr: false }),
  'css-keyframes': dynamic(() => import('../components/tools/instances/CssGradientGenerator'), { ssr: false }),
  'css-color-extractor': dynamic(() => import('../components/tools/instances/ColorPicker'), { ssr: false }),
  
  // Batch 6: AI & LLM Engineering
  'prompt-token-calculator': dynamic(() => import('../components/tools/instances/TokenCalculator'), { ssr: false }),
  'rag-optimizer': dynamic(() => import('../components/tools/instances/RagOptimizer'), { ssr: false }),

  // Batch 7: Modern ORM & Database

  // Batch 8: Cloud-Native & DevOps
  'k8s-yaml-validator': dynamic(() => import('../components/tools/instances/K8sYamlValidator'), { ssr: false }),
  'aws-iam-generator': dynamic(() => import('../components/tools/instances/AwsIamGenerator'), { ssr: false }),
  'cron-to-k8s': dynamic(() => import('../components/tools/instances/CronToK8s'), { ssr: false }),
}
