'use client'


import React, { ComponentType, lazy } from 'react'

export const TOOL_COMPONENTS: Record<string, ComponentType<any>> = {
  'json-to-code-generator': lazy(() => import('../components/tools/instances/JsonToCodeGenerator')),
  'json-yaml-jsonl-converter': lazy(() => import('../components/tools/instances/JsonYamlJsonlConverter')),
  'bulk-uuid-v4-v7-generator': lazy(() => import('../components/tools/instances/BulkUuidGenerator')),
  'password-entropy-tester': lazy(() => import('../components/tools/instances/PasswordEntropyTester')),
  'csv-json-xml-converter': lazy(() => import('../components/tools/instances/CsvJsonXmlConverter')),

  
  // Wave 2 Consolidated Masters
  'schema-markup-generator': lazy(() => import('../components/tools/instances/SchemaMarkupGenerator')),
  'sql-toolkit': lazy(() => import('../components/tools/instances/SqlToolkit')),
  'markdown-html-converter': lazy(() => import('../components/tools/instances/MarkdownHtmlConverter')),

  
  // Wave 3 Consolidated Masters
  'binary-hex-decimal-converter': lazy(() => import('../components/tools/instances/BinaryHexDecimalConverter')),
  'base64-encoder-decoder': lazy(() => import('../components/tools/instances/Base64EncoderDecoder')),
  'text-case-formatter': lazy(() => import('../components/tools/instances/TextCaseFormatter')),
  'jwt-decoder-generator': lazy(() => import('../components/tools/instances/JwtDecoderGenerator')),

  
  // Wave 4 Consolidated Masters
  'css-formatter-minifier': lazy(() => import('../components/tools/instances/CssFormatterMinifier')),
  'css-generators': lazy(() => import('../components/tools/instances/CssGenerators')),
  'robots-txt-toolkit': lazy(() => import('../components/tools/instances/RobotsTxtToolkit')),
  'color-converter': lazy(() => import('../components/tools/instances/ColorConverter')),
  'px-rem-converter': lazy(() => import('../components/tools/instances/PxRemConverter')),

  // Batch 1: Core Utilities
  'what-is-my-ip': lazy(() => import('../components/tools/instances/WhatIsMyIP')),
  'js-minifier': lazy(() => import('../components/tools/instances/JsMinifier')),
  'meta-tag-generator': lazy(() => import('../components/tools/instances/MetaTagGenerator')),
  'lorem-ipsum': lazy(() => import('../components/tools/instances/LoremIpsum')),
  'hash-generator': lazy(() => import('../components/tools/instances/HashGenerator')),
  
  // Batch 2: SEO & Validation
  'sitemap-validator': lazy(() => import('../components/tools/instances/SitemapValidator')),
  'redirect-checker': lazy(() => import('../components/tools/instances/RedirectChecker')),
  'api-latency-calculator': lazy(() => import('../components/tools/instances/ApiLatencyCalculator')),
  'adsense-calculator': lazy(() => import('../components/tools/instances/AdSenseCalculator')),
  'xml-to-yaml': lazy(() => import('../components/tools/instances/XmlToYaml')),
  'css-unit-converter': lazy(() => import('../components/tools/instances/CssUnitConverter')),
  'url-encoder': lazy(() => import('../components/tools/instances/UrlEncoder')),
  
  // Batch 3: Design & Media
  'cdn-readiness-tester': lazy(() => import('../components/tools/instances/CdnReadinessTester')),
  'color-contrast': lazy(() => import('../components/tools/instances/ColorContrast')),
  'html-encoder': lazy(() => import('../components/tools/instances/HtmlEncoder')),
  'timestamp-converter': lazy(() => import('../components/tools/instances/TimestampConverter')),
  
  // Batch 4: Formatting & Code
  'social-preview-tester': lazy(() => import('../components/tools/instances/SocialPreviewTester')),
  'question-explorer': lazy(() => import('../components/tools/instances/QuestionExplorer')),
  'html-beautifier': lazy(() => import('../components/tools/instances/HtmlBeautifier')),
  'regex-tester': lazy(() => import('../components/tools/instances/RegexTester')),
  'regex-explainer': lazy(() => import('../components/tools/instances/RegexExplainer')),
  'cron-generator': lazy(() => import('../components/tools/instances/CronGenerator')),
  'diff-checker': lazy(() => import('../components/tools/instances/CodeDiff')),
  'code-diff': lazy(() => import('../components/tools/instances/CodeDiff')),
  'llms-txt-generator': lazy(() => import('../components/tools/instances/LlmsTxtGenerator')),
  'slug-generator': lazy(() => import('../components/tools/instances/SlugGenerator')),
  'htaccess-generator': lazy(() => import('../components/tools/instances/HtaccessGenerator')),
  'favicon-generator': lazy(() => import('../components/tools/instances/FaviconGenerator')),
  'xml-formatter': lazy(() => import('../components/tools/instances/XmlFormatter')),
  'xml-minifier': lazy(() => import('../components/tools/instances/XmlMinifier')),
  'qr-code-generator': lazy(() => import('../components/tools/instances/QrCodeGenerator')),
  'php-serializer': lazy(() => import('../components/tools/instances/PhpSerializer')),
  'image-resizer': lazy(() => import('../components/tools/instances/ImageResizer')),

  // Batch 5: Security & Data
  'xss-scanner': lazy(() => import('../components/tools/instances/XssScanner')),
  'yaml-to-json': lazy(() => import('../components/tools/instances/YamlToJson')),
  'aes-encryption': lazy(() => import('../components/tools/instances/AesEncryption')),
  'sri-hasher': lazy(() => import('../components/tools/instances/SriHasher')),
  'csp-builder': lazy(() => import('../components/tools/instances/CspBuilder')),
  'file-checksum': lazy(() => import('../components/tools/instances/FileChecksum')),
  'permissions-policy': lazy(() => import('../components/tools/instances/PermissionsPolicy')),
  'meta-length-checker': lazy(() => import('../components/tools/instances/MetaLengthChecker')),
  'heading-visualizer': lazy(() => import('../components/tools/instances/HeadingVisualizer')),
  'og-debugger': lazy(() => import('../components/tools/instances/OgDebugger')),
  'twitter-card-gen': lazy(() => import('../components/tools/instances/TwitterCardGen')),
  'nginx-generator': lazy(() => import('../components/tools/instances/NginxGenerator')),
  'docker-compose-gen': lazy(() => import('../components/tools/instances/DockerComposeGen')),
  'dotenv-generator': lazy(() => import('../components/tools/instances/DotenvGenerator')),
  'pwa-manifest': lazy(() => import('../components/tools/instances/PwaManifest')),
  'emoji-picker': lazy(() => import('../components/tools/instances/EmojiPicker')),
  'readability-checker': lazy(() => import('../components/tools/instances/ReadabilityChecker')),
  'html-to-markdown': lazy(() => import('../components/tools/instances/HtmlToMarkdown')),
  'url-parser': lazy(() => import('../components/tools/instances/UrlParser')),
  'ua-parser': lazy(() => import('../components/tools/instances/UaParser')),
  'ascii-art': lazy(() => import('../components/tools/instances/AsciiArt')),
  'morse-code': lazy(() => import('../components/tools/instances/MorseCode')),
  'html-entities': lazy(() => import('../components/tools/instances/HtmlEntities')),
  'text-similarity': lazy(() => import('../components/tools/instances/TextSimilarity')),
  'keyword-density': lazy(() => import('../components/tools/instances/KeywordDensity')),
  'slug-optimizer': lazy(() => import('../components/tools/instances/SlugOptimizer')),
  'html-minifier': lazy(() => import('../components/tools/instances/HtmlMinifier')),
  'js-obfuscator': lazy(() => import('../components/tools/instances/JsObfuscator')),
  'js-evaluator': lazy(() => import('../components/tools/instances/JsEvaluator')),
  'curl-converter': lazy(() => import('../components/tools/instances/CurlConverter')),
  'json-schema-gen': lazy(() => import('../components/tools/instances/JsonSchemaGen')),
  'data-anonymizer': lazy(() => import('../components/tools/instances/DataAnonymizer')),
  'dom-analyzer': lazy(() => import('../components/tools/instances/DomAnalyzer')),
  'html-table-to-json': lazy(() => import('../components/tools/instances/HtmlTableToJson')),
  'cron-descriptor': lazy(() => import('../components/tools/instances/CronDescriptor')),
  'percentage-calc': lazy(() => import('../components/tools/instances/PercentageCalc')),
  'aspect-ratio-calc': lazy(() => import('../components/tools/instances/AspectRatioCalc')),
  'word-counter': lazy(() => import('../components/tools/instances/WordCounter')),
  'character-counter': lazy(() => import('../components/tools/instances/CharacterCounter')),
  'line-counter': lazy(() => import('../components/tools/instances/LineCounter')),
  'rot13-cipher': lazy(() => import('../components/tools/instances/Rot13Cipher')),
  'rsa-key-gen': lazy(() => import('../components/tools/instances/RsaKeyGen')),
  'random-user-gen': lazy(() => import('../components/tools/instances/RandomUserGen')),
  'credit-card-validator': lazy(() => import('../components/tools/instances/CreditCardValidator')),
  'iban-validator': lazy(() => import('../components/tools/instances/IbanValidator')),
  'nanoid-gen': lazy(() => import('../components/tools/instances/NanoidGen')),
  'barcode-gen': lazy(() => import('../components/tools/instances/BarcodeGen')),
  'svg-optimizer': lazy(() => import('../components/tools/instances/SvgOptimizer')),
  'domain-age-checker': lazy(() => import('../components/tools/instances/DomainAgeChecker')),
  'subnet-calculator': lazy(() => import('../components/tools/instances/SubnetCalculator')),
  'port-scanner': lazy(() => import('../components/tools/instances/PortScanner')),
  'contrast-checker': lazy(() => import('../components/tools/instances/ContrastChecker')),
  'bcrypt-hasher': lazy(() => import('../components/tools/instances/BcryptHasher')),
  'argon2-hasher': lazy(() => import('../components/tools/instances/Argon2Hasher')),
  'scrypt-hasher': lazy(() => import('../components/tools/instances/ScryptHasher')),
  'hmac-generator': lazy(() => import('../components/tools/instances/HmacGenerator')),
  'dns-propagation': lazy(() => import('../components/tools/instances/DnsPropagation')),
  'ssl-checker': lazy(() => import('../components/tools/instances/SslChecker')),
  'ping-test': lazy(() => import('../components/tools/instances/PingTest')),
  'whois-lookup': lazy(() => import('../components/tools/instances/WhoisLookup')),
  'http-headers-inspector': lazy(() => import('../components/tools/instances/HttpHeadersInspector')),
  'broken-link-checker': lazy(() => import('../components/tools/instances/BrokenLinkChecker')),
  'site-audit-pro': lazy(() => import('../components/tools/instances/SiteAuditPro')),
  'sitemap-generator': lazy(() => import('../components/tools/instances/SitemapGenerator')),
  'load-time-estimator': lazy(() => import('../components/tools/instances/LoadTimeEstimator')),
  'responsive-checker-pro': lazy(() => import('../components/tools/instances/ResponsiveCheckerPro')),
  'color-blind-simulator': lazy(() => import('../components/tools/instances/ColorBlindSimulator')),
  'image-compressor-pro': lazy(() => import('../components/tools/instances/ImageCompressorPro')),
  'pdf-to-text-extractor': lazy(() => import('../components/tools/instances/PdfToTextExtractor')),
  'text-to-speech-pro': lazy(() => import('../components/tools/instances/TextToSpeechPro')),
  'alt-text-auditor': lazy(() => import('../components/tools/instances/AltTextAuditor')),
  'authority-simulator': lazy(() => import('../components/tools/instances/AuthoritySimulator')),
  'browser-compat-checker': lazy(() => import('../components/tools/instances/BrowserCompatChecker')),
  'canonical-checker': lazy(() => import('../components/tools/instances/CanonicalChecker')),
  'hreflang-generator': lazy(() => import('../components/tools/instances/HreflangGenerator')),
  'snippet-preview': lazy(() => import('../components/tools/instances/SnippetPreview')),
  'webhook-visualizer': lazy(() => import('../components/tools/instances/WebhookVisualizer')),
  'storage-auditor': lazy(() => import('../components/tools/instances/StorageAuditor')),
  'ip-geolocation': lazy(() => import('../components/tools/instances/WhatIsMyIP')),
  'mobile-meta-gen': lazy(() => import('../components/tools/instances/MetaTagGenerator')),
  'redirect-chain-finder': lazy(() => import('../components/tools/instances/RedirectChecker')),
  'cdn-finder': lazy(() => import('../components/tools/instances/CdnReadinessTester')),
  'data-masking': lazy(() => import('../components/tools/instances/DataAnonymizer')),
  'git-helper': lazy(() => import('../components/tools/instances/GitHelper')),
  'hsts-gen': lazy(() => import('../components/tools/instances/CspBuilder')),
  'js-execution-audit': lazy(() => import('../components/tools/instances/SiteAuditPro')),
  'resource-priority': lazy(() => import('../components/tools/instances/MetaTagGenerator')),
  'network-throttling': lazy(() => import('../components/tools/instances/ApiLatencyCalculator')),
  'compression-test': lazy(() => import('../components/tools/instances/SiteAuditPro')),
  
  // Batch 6: AI & LLM Engineering
  'prompt-token-calculator': lazy(() => import('../components/tools/instances/TokenCalculator')),
  'rag-optimizer': lazy(() => import('../components/tools/instances/RagOptimizer')),

  // Batch 7: Modern ORM & Database

  // Batch 8: Cloud-Native & DevOps
  'k8s-yaml-validator': lazy(() => import('../components/tools/instances/K8sYamlValidator')),
  'aws-iam-generator': lazy(() => import('../components/tools/instances/AwsIamGenerator')),
  'cron-to-k8s': lazy(() => import('../components/tools/instances/CronToK8s')),
}
