'use client'




export const TOOL_FILES: Record<string, string> = {
  'json-to-code-generator': 'JsonToCodeGenerator',
  'json-yaml-jsonl-converter': 'JsonYamlJsonlConverter',
  'bulk-uuid-v4-v7-generator': 'BulkUuidGenerator',
  'password-entropy-tester': 'PasswordEntropyTester',
  'csv-json-xml-converter': 'CsvJsonXmlConverter',

  
  // Wave 2 Consolidated Masters
  'schema-markup-generator': 'SchemaMarkupGenerator',
  'sql-toolkit': 'SqlToolkit',
  'markdown-html-converter': 'MarkdownHtmlConverter',

  
  // Wave 3 Consolidated Masters
  'binary-hex-decimal-converter': 'BinaryHexDecimalConverter',
  'base64-encoder-decoder': 'Base64EncoderDecoder',
  'text-case-formatter': 'TextCaseFormatter',
  'jwt-decoder-generator': 'JwtDecoderGenerator',

  
  // Wave 4 Consolidated Masters
  'css-formatter-minifier': 'CssFormatterMinifier',
  'css-generators': 'CssGenerators',
  'robots-txt-toolkit': 'RobotsTxtToolkit',
  'color-converter': 'ColorConverter',
  'px-rem-converter': 'PxRemConverter',

  // Batch 1: Core Utilities
  'what-is-my-ip': 'WhatIsMyIP',
  'js-minifier': 'JsMinifier',
  'meta-tag-generator': 'MetaTagGenerator',
  'lorem-ipsum': 'LoremIpsum',
  'hash-generator': 'HashGenerator',
  
  // Batch 2: SEO & Validation
  'sitemap-validator': 'SitemapValidator',
  'redirect-checker': 'RedirectChecker',
  'api-latency-calculator': 'ApiLatencyCalculator',
  'adsense-calculator': 'AdSenseCalculator',
  'xml-to-yaml': 'XmlToYaml',
  'css-unit-converter': 'CssUnitConverter',
  'url-encoder': 'UrlEncoder',
  
  // Batch 3: Design & Media
  'cdn-readiness-tester': 'CdnReadinessTester',
  'color-contrast': 'ColorContrast',
  'html-encoder': 'HtmlEncoder',
  'timestamp-converter': 'TimestampConverter',
  
  // Batch 4: Formatting & Code
  'social-preview-tester': 'SocialPreviewTester',
  'question-explorer': 'QuestionExplorer',
  'html-beautifier': 'HtmlBeautifier',
  'regex-tester': 'RegexTester',
  'regex-explainer': 'RegexExplainer',
  'cron-generator': 'CronGenerator',
  'diff-checker': 'CodeDiff',
  'code-diff': 'CodeDiff',
  'llms-txt-generator': 'LlmsTxtGenerator',
  'slug-generator': 'SlugGenerator',
  'htaccess-generator': 'HtaccessGenerator',
  'favicon-generator': 'FaviconGenerator',
  'xml-formatter': 'XmlFormatter',
  'xml-minifier': 'XmlMinifier',
  'qr-code-generator': 'QrCodeGenerator',
  'php-serializer': 'PhpSerializer',
  'image-resizer': 'ImageResizer',

  // Batch 5: Security & Data
  'xss-scanner': 'XssScanner',
  'yaml-to-json': 'YamlToJson',
  'aes-encryption': 'AesEncryption',
  'sri-hasher': 'SriHasher',
  'csp-builder': 'CspBuilder',
  'file-checksum': 'FileChecksum',
  'permissions-policy': 'PermissionsPolicy',
  'meta-length-checker': 'MetaLengthChecker',
  'heading-visualizer': 'HeadingVisualizer',
  'og-debugger': 'OgDebugger',
  'twitter-card-gen': 'TwitterCardGen',
  'nginx-generator': 'NginxGenerator',
  'docker-compose-gen': 'DockerComposeGen',
  'dotenv-generator': 'DotenvGenerator',
  'pwa-manifest': 'PwaManifest',
  'emoji-picker': 'EmojiPicker',
  'readability-checker': 'ReadabilityChecker',
  'html-to-markdown': 'HtmlToMarkdown',
  'url-parser': 'UrlParser',
  'ua-parser': 'UaParser',
  'ascii-art': 'AsciiArt',
  'morse-code': 'MorseCode',
  'html-entities': 'HtmlEntities',
  'text-similarity': 'TextSimilarity',
  'keyword-density': 'KeywordDensity',
  'slug-optimizer': 'SlugOptimizer',
  'html-minifier': 'HtmlMinifier',
  'js-obfuscator': 'JsObfuscator',
  'js-evaluator': 'JsEvaluator',
  'curl-converter': 'CurlConverter',
  'json-schema-gen': 'JsonSchemaGen',
  'data-anonymizer': 'DataAnonymizer',
  'dom-analyzer': 'DomAnalyzer',
  'html-table-to-json': 'HtmlTableToJson',
  'cron-descriptor': 'CronDescriptor',
  'percentage-calc': 'PercentageCalc',
  'aspect-ratio-calc': 'AspectRatioCalc',
  'word-counter': 'WordCounter',
  'character-counter': 'CharacterCounter',
  'line-counter': 'LineCounter',
  'rot13-cipher': 'Rot13Cipher',
  'rsa-key-gen': 'RsaKeyGen',
  'random-user-gen': 'RandomUserGen',
  'credit-card-validator': 'CreditCardValidator',
  'iban-validator': 'IbanValidator',
  'nanoid-gen': 'NanoidGen',
  'barcode-gen': 'BarcodeGen',
  'svg-optimizer': 'SvgOptimizer',
  'domain-age-checker': 'DomainAgeChecker',
  'subnet-calculator': 'SubnetCalculator',
  'port-scanner': 'PortScanner',
  'contrast-checker': 'ContrastChecker',
  'bcrypt-hasher': 'BcryptHasher',
  'argon2-hasher': 'Argon2Hasher',
  'scrypt-hasher': 'ScryptHasher',
  'hmac-generator': 'HmacGenerator',
  'dns-propagation': 'DnsPropagation',
  'ssl-checker': 'SslChecker',
  'ping-test': 'PingTest',
  'whois-lookup': 'WhoisLookup',
  'http-headers-inspector': 'HttpHeadersInspector',
  'broken-link-checker': 'BrokenLinkChecker',
  'site-audit-pro': 'SiteAuditPro',
  'sitemap-generator': 'SitemapGenerator',
  'load-time-estimator': 'LoadTimeEstimator',
  'responsive-checker-pro': 'ResponsiveCheckerPro',
  'color-blind-simulator': 'ColorBlindSimulator',
  'image-compressor-pro': 'ImageCompressorPro',
  'pdf-to-text-extractor': 'PdfToTextExtractor',
  'text-to-speech-pro': 'TextToSpeechPro',
  'alt-text-auditor': 'AltTextAuditor',
  'authority-simulator': 'AuthoritySimulator',
  'browser-compat-checker': 'BrowserCompatChecker',
  'canonical-checker': 'CanonicalChecker',
  'hreflang-generator': 'HreflangGenerator',
  'snippet-preview': 'SnippetPreview',
  'webhook-visualizer': 'WebhookVisualizer',
  'storage-auditor': 'StorageAuditor',
  'ip-geolocation': 'WhatIsMyIP',
  'mobile-meta-gen': 'MetaTagGenerator',
  'redirect-chain-finder': 'RedirectChecker',
  'cdn-finder': 'CdnReadinessTester',
  'data-masking': 'DataAnonymizer',
  'git-helper': 'GitHelper',
  'hsts-gen': 'CspBuilder',
  'js-execution-audit': 'SiteAuditPro',
  'resource-priority': 'MetaTagGenerator',
  'network-throttling': 'ApiLatencyCalculator',
  'compression-test': 'SiteAuditPro',
  
  // Batch 6: AI & LLM Engineering
  'prompt-token-calculator': 'TokenCalculator',
  'rag-optimizer': 'RagOptimizer',

  // Batch 7: Modern ORM & Database

  // Batch 8: Cloud-Native & DevOps
  'k8s-yaml-validator': 'K8sYamlValidator',
  'aws-iam-generator': 'AwsIamGenerator',
  'cron-to-k8s': 'CronToK8s',
}
